### ISSUE TITLE
NotMember?

### ISSUE THREAD

**Issue by agocorona** [dorchard/type-level-sets#10]
I'm continuing exploring the amazing expressiveness of your library for making rich type signatures and that are good both for the human reader as documentation and for the compiler to codifying invariants:

Let's say that `collect` can collect the output of some jobs and return a list of data with all the results. But obviously it can not do with infinite streams.

It return the result in a single thread and blocks until the results are available:

    collect :: (NotMember Streaming effs) => TRS effs  a 
                -> TRS (effs :\Asynchronous  :\ MultiThreaded) [a] 

That is Ok except  `NotMember` which is not defined

**Comment by agocorona** [comment]
I just remembered that the actual `collect` [here](https://github.com/transient-haskell/transient/blob/master/src/Transient/Indeterminism.hs#L105)  does not keep any state that may have been present in the argument:
Since state is polymorphic, I defined an effect   `State a`.   That means that a computation can keep multiple states, one of each type. Could I code this in some way?

      collect :: (NotMember Streaming effs) => TRS effs  a 
               -> TRS (effs :\Asynchronous  :\ MultiThreaded  :\  State x) [a]

**Comment by agocorona** [comment]
unsetStates :: effs ->( effs :\ AllStates) 

How can I have a  instance   effs  :\  AllStates  so that it can delete all "State a". is it possible?

In general  some  class `Delete Set b`    for all the elements of the set which are "equal" is some way would be nice

**Comment by ivanperez-keera** [comment]
I'm not sure I'm understanding this 100% right, but I'd also be interested in representing 'Not a member of a set' in a type constraint.

**Comment by agocorona** [comment]
Ivan, my question has a lot of context that has nothing to do with type-level-sets but with my intended use of it, Sorry. In essence it is just having notMember as a constraint. or something equivalent. I don't know if
some type-level filtering plus equality could do the job.

**Comment by agocorona** [comment]
filtering by a type-level lambda would do a lot of tricks

**Comment by agocorona** [comment]
Any advance on that?
@dorchard  I can try to do it myself and send a pull request but I need some hint...

**Comment by agocorona** [comment]
I see that NonMember is implemented time ago. I close it. thanks!
