### ISSUE TITLE
Eq and Show instances

### ISSUE THREAD

**Issue by jkarni** [dorchard/type-level-sets#6]
`Map` and `Set` are missing `Eq` and `Show` instances. These should be pretty similar to HList's.

**Comment by dorchard** [comment]
Fixed in commit https://github.com/dorchard/type-level-sets/commit/3cca261595ab1b25ef427ad456199bb6e68da08a
There is already a `Show` instance. I just added `Eq`. Pushed to hackage as version 0.8.0.0
