### ISSUE TITLE
How to eliminate elements in the set?

### ISSUE THREAD

**Issue by agocorona** [dorchard/type-level-sets#8]
I'm trying to use your type-level-sets  at a first attempt and later your graded monad to codify effects of my monad. I know how to aggregate effects , But how to remove them?. Oleg Extensible Effects has an operator that is used to "remove" an Effect from the list. 

runState :: Typeable s ⇒ Eff (State s  !> r ) w → s → Eff r (w,s)

So he can remove `State s` from the result. That is what I would like to do

**Comment by dorchard** [comment]
Hi! Yes this can be done and I am very happy to add this. I've made a first approximation in commit bbf1690581e73a81e077f998e7796585c71b1024 which is based on type-equality, and has a corresponding value-level counterpart. Does this do what you need it to? Otherwise we can iterate together to get something that works with your setup. 

(sorry I am on vacation at the moment so replies may be delayed).

**Comment by agocorona** [comment]
Hi. Thanks!

I don´t know if I'm using it well.  I have defined:

`streamProc` has the streaming effect.  there is a primitive `collect` that read a stream and create an array. So it "removes" the streaming effect. I try to simulate the effect of collect  with `removeStream` .

Then I try to make sure of that by using a primitive  `doWithStream` to verify that GHC report an error. 


```
data TR eff m a= TR  (m a) deriving(Applicative, A.Alternative)
type TRS effs a = TR (Set effs) Tr.TransIO a 

data Streaming 

removeStream :: TRS effs  a -> TRS ( effs :\ Streaming)  a
removeStream = coerceEffs . id

doWithStream ::  (Subset '[Streaming] effs) => TRS effs  a -> TRS effs a
doWithStream= coerceEffs . id 

coerceEffs :: TR effs m a -> TR effs' m a
coerceEffs (TR comp)= TR comp


streamProc :: TRS '[Streaming] String
streamProc= undefined

expr=  doWithStream $ removeStream   streamProc  -- error OK: No instance for (Subset '[Streaming] '[])  
expr1= doWithStream streamProc   -- Overlapping instances .for Subset '[Streaming] '[Streaming]
```
Are my definitions for doWitStream and removeStream correct?

expr error is OK, but how I can avoid the second one?

Another question is that when using Nub and Sort the type signatures are quite complex. I don´t know if this is something we have to live with or there is a way to overcome it.

I have these definitions
```
async ::  IO a -> TRS '[Asynchronous,MultiThreaded]  a
async = TR . Tr.async 

waitEvents :: IO a -> TRS ( '[Streaming,MultiThreaded])  a
waitEvents = TR . Tr.waitEvents

-- threads0 :: TRS effs a -> TRS (Filter MultiThreaded effs ) a
-- threads0= TR . threads 0

(<|>) ::  TRS effs a -> TRS effs' a -> TRS (Union effs  effs') a
TR a <|> TR b=  TR $  a A.<|>  b
```

then   `async (return "hello") <|> waitEvents (return "world")`  has type  
```
TRS
       (Union '[Asynchronous, MultiThreaded] '[Streaming, MultiThreaded])
       ()
```
Not very bad, but it can become really complex
if i define  <|>  with  (effs :++ effs')  instead of  `Union effs effs'   the type is nicer, but there are repeated elements:  `TRS '[[Asynchronous, MultiThreaded, Streaming, MultiThreaded]`

**Comment by agocorona** [comment]
@dorchard (Just in case you forgot the above response)

**Comment by dorchard** [comment]
Sorry about that! I was missing appropriate overlapping pragrams for subsets. This is now fixed in the latest commit 28fe8b8b99bc6e0debc2451e4299ad463cf534f8 and version 0.8.6.0 on Hackage. 

Regarding the normalising steps (Nub/IF/Sort), what is missing from your example is that you need to tell the library how the different elements, `Asnychrnous`, `MultiThreaded`, etc. are ordered, otherwise it cannot do the normalisation to remove duplicates.

So perhaps try the following (import Data.Type.Bool and Data.Type.Equality)
```
data TR eff m a= TR  (m a) deriving(Applicative, Functor)
type TRS (effs :: [Mode]) a = TR (Set effs) IO a

data Mode = Streaming | MultiThreaded | Asynchronous

type family CmpModes (a :: Mode) (b :: Mode) :: Ordering where
            CmpModes Asynchronous MultiThreaded = LT
            CmpModes Asynchronous Streaming     = LT
            CmpModes MultiThreaded Streaming    = LT
            CmpModes a a                        = EQ
            CmpModes a b                        =
               If (CmpModes b a == LT) GT (CmpModes b a)

type instance Cmp (a :: Mode) (b :: Mode) = CmpModes a b
```
Now when I do 
```
foo = async (return "hello") <|> waitEvents (return "world")
```
GHC infers the type as: `foo :: TRS '['Asynchronous, 'MultiThreaded, 'Streaming] [Char]`, which I think is what you want?

**Comment by dorchard** [comment]
Btw, I just added a `Member` predicate as well so you can write
```
doWithStream ::  (Member Streaming effs) => TRS effs a -> TRS effs a
```
instead of
```
doWithStream ::  (Subset '[Streaming] effs) => TRS effs a -> TRS effs a
```
(this is  in the last commit and I've made a new version on hackage as well, 0.8.7.0, which also incorporates a few more tweaks for flexibility).

**Comment by agocorona** [comment]
Great! 

Is a great relief for me to know that these big expressions can be reduced and it is not a inherent shortcoming of the model. I will test it ASAP

**Comment by agocorona** [comment]
type TRS (effs :: [Mode] ) a = TR (Set effs) IO a 

In the second "effs"  I have:
```
* Expected kind `[*]', but `effs' has kind `[Mode]'
    * In the first argument of `Set', namely `effs'
      In the first argument of `TR', namely `Set effs'
      In the type `TR (Set effs) Tr.TransIO a'
``

**Comment by dorchard** [comment]
Hi! I changed the kinding of `Set` to allow this. Are you sure you're using the latest commit / version 0.8.7.0 (from Hackage, not yet on Stackage I guess....) ?

**Comment by dorchard** [comment]
(indeed I don't think effect-monad or type-level-sets are on Stackage-- changing that now-- which might have been a problem here ... not sure).

**Comment by agocorona** [comment]
mmm
No.  You're right . Stack refused to install from git.
Now with the new version I have a panic! (the 'impossible' happened)
      (GHC version 8.0.1 for x86_64-unknown-mingw32):

I suppose that I have to upgrade te ghc version

**Comment by dorchard** [comment]
Quite possibly...! Sorry I only tested this with 8.2.2

**Comment by agocorona** [comment]
Awesome. It works as expected with the ghc 8.2.2.  So I can create my rules to discard wrong compositions of combinators.

There is one thing that would make it  even better ; the list of effects can be open?

 May be wonderful if the application programmer could define their own effects: For example, an e-commerce application programmer may define some additional effects:

Pay, HasCartProducts

so that:
pay ::  Member HasCartProducts effs => m (Union Pay (effs :\ HasCartProducts) ) ()

addCart :: NotMember  prod -> m [HasCaetProducts] ()

so that all addCart acctions are done before a single payment and  no adding to cart is done after the payment for that branch of the computation.

**Comment by agocorona** [comment]
I also would need that kind of freedom to allow different Sate types, defined by  the application programmer:

     '[State Bool. State Cart, State myData....]

Without the states being known at monad definition time, if this is possible.

I suspect that it would multiply the Cmp instance definitions. I don't know  if there is a trick for that.

**Comment by agocorona** [comment]
OK OK, I verified that it just works by defining the elements (effects) as separate types ; 

      data Streaming
      data Multihreaded
      ...

the only caveat is that the Comparison is made in a single class, so the programmer must add elements to it to add new effects so it must touch the library. Can this be avoided?  I think so but I'm not well versed in type extensions to figure it out.

**Comment by dorchard** [comment]
Yes- the list of effects can be open. I made it closed in this example but only because I wanted to make a compact definition for `Cmp` as you've inferred. It makes a lot of sense to make it open, so that might be the most useful thing here- I'm glad you got that working. You could also define an extensible data type like:
```
data Mode a = Streaming | MultiThreaded | Asynchronous | Custom a
```
which might work out quite well if you want to fix a core but have an extensible part via `Custom`?

With regards your last question: do you mean adding instances to `Cmp`? This can be done in any module that imports `Data.Type.Set`.

**Comment by agocorona** [comment]
Thanks. got it.
