### ISSUE TITLE
Custom compile-time errors 

### ISSUE THREAD

**Issue by agocorona** [dorchard/type-level-sets#9]
Custom compile errors are described in:

https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/glasgow_exts.html#custom-compile-time-errors

It  may be very useful for making type errors more understandable. For example, in a computation `doWithStream` that expect the `Streaming` effect in his argument, the compiler report this error when this effect is not present:

       No instance for (Member 'Streaming '[])
                  arising from a use of `doWithStream'
             * In a stmt of a 'do' block:

It is not very bad,  but a more concrete error "Streaming effect neeeded  arising from a use of..." or something similar

I'm not sure if this is doable. It seems so.

**Comment by agocorona** [comment]
But this does not make sense in type-level-list package. It is meaningful in an effect library.

**Comment by o1lo01ol1o** [comment]
Taken from @isovector 's "Thinking with Types"

```
> show id
<interactive>:2:1: error:•
No instance for (Show (a0 -> a0)) arising from
􏰇→ a use of ‘’show
(maybe you haven't applied a function to
􏰇→ enough arguments?)•
 ```

```haskell
{-# LANGUAGE DataKinds            #-}
{-# LANGUAGE TypeOperators        #-}
{-# LANGUAGE UndecidableInstances #-}
instance
( TypeError
( Text "Attempting to show a function of type `"
:<>: ShowType (a -> b)
:<>: Text "'"
:$$: Text "Did you forget to apply an argument?"
) )=>Show(a->b)where
show = undefined
```
```
Attempting to show a function of type `a0 ->
􏰇→ a0'
Did you forget to apply an argument?•
In the expression: show id
In an equation for ‘’it: it = show id
```

**Comment by o1lo01ol1o** [comment]
Then, using `first-class-famlies`:
```haskell
type family FriendlyFindElem (f :: k -> Type) (t :: k) (ts :: [k]) 􏰇→ where
FriendlyFindElem f t ts = FromMaybe
( TypeError
( 'Text "Attempted to call `friendlyPrj' to produce a `" ':<>: 'ShowType (f t)
':<>: 'Text "'."
':$$: 'Text "But the OpenSum can only contain one of:" ':$$: 'Text " "
':<>: 'ShowType ts
)) =<< FindIndex (TyEq t) ts
```
